version: "3.7"

services:
  db:
    container_name: database
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=rest-api-db
    ports:
    - "3306:3306"